# Generated by Django 3.2.8 on 2021-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customized_info',
            name='desc',
            field=models.CharField(default='', max_length=400),
        ),
    ]
